import { Schema } from "mongoose";

export const courseSechema = new Schema({
    image:{
        type:String,
        required:true
    },
    name:{
        type:String,
        required:true
    },
    desc:{
        type:String,
        required:true
    },
    
    duration:{
        type:String,
        required:true
    },
    type:{
        type:String,
        required:true
    },
    level:{
        type:String,
        required:true
    },
    language:{
        type:String,
        required:true
    },
    instructor:{
        type:Object,
        required:true
    },
    ratings:Array<Object>,
    promovideo:{
        type:String,
        required:true
    },
    module:Array<Object>,
    price:{
        type:String,
        required:true
    },
    student:{
        type:Number,
        required:true
    },
    certifications:{
        type:Boolean,
        default:false
    },
    lessons:{
        type:Number,
        required:true
    },
    promocodes:{
        type:Array<Object>
    },
    pendingStudents:Array<String>,
    courseStudents:Array<String>
})