import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Common/Footer";
import Navbar from "@/components/Common/Navbar";
import StoreProvider from "./StoreProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <StoreProvider>
          <Navbar />

          {children}
          <Toaster
          position="top-center"/>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
